---

- name: create_directories
  file:
    owner: "{{ item.uid }}"
    group: "{{ item.gid }}"
    path: "{{ item.directory_path }}"
    mode: "{{ item.mode }}"
    recurse: yes
    state: directory
  become: true
  loop: "{{ folders_list }}"
  when: >
    item.create is defined and
    item.create